=== Vedkhajone/WTL/Web_Technology_2026_Lab_Assignments/Assignment_02/catalog.dtd
<!ELEMENT university (address,department+, student+)>

<!ELEMENT address (#PCDATA)>

<!ELEMENT department (dept_name, faculty+, course+)>
<!ATTLIST department dept_code ID #REQUIRED>

<!ELEMENT dept_name (#PCDATA)>


<!ELEMENT faculty (faculty_name, designation, email)>
<!ATTLIST faculty phone CDATA #IMPLIED>

<!ELEMENT faculty_name (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT email (#PCDATA)>


<!ELEMENT course (course_title, credits, semester)>
<!ATTLIST course course_code ID #REQUIRED>

<!ELEMENT course_title (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ELEMENT semester (#PCDATA)>


<!ELEMENT student (student_name, enrolled_courses)>
<!ATTLIST student
    student_id ID #REQUIRED
    dept_ref IDREF #REQUIRED>

<!ELEMENT student_name (#PCDATA)>
<!ELEMENT enrolled_courses (#PCDATA)>

=== Vedkhajone/WTL/Web_Technology_2026_Lab_Assignments/Assignment_02/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE university SYSTEM "catalog.dtd">

<university>
    <address>Kopargaon, Maharashtra</address>

    <department dept_code="D1">
        <dept_name>Electronics</dept_name>

        <faculty phone="9876543210">
            <faculty_name>Dr.XYZ</faculty_name>
            <designation>Professor</designation>
            <email>xyz@gmail.com.com</email>
        </faculty>

        <faculty>
            <faculty_name>Prof. ABC</faculty_name>
            <designation>Assistant Professor</designation>
            <email>abc@gmail.com.com</email>
        </faculty>

        <course course_code="C1">
            <course_title>Java</course_title>
            <credits>4</credits>
            <semester>3</semester>
        </course>

        <course course_code="C2">
            <course_title>DBMS</course_title>
            <credits>3</credits>
            <semester>5</semester>
        </course>

    </department>

   
    <student student_id="S1" dept_ref="D1">
        <student_name>Pradnya</student_name>
        <enrolled_courses>C1,C2</enrolled_courses>
    </student>


</university>
