=== Vedkhajone/WTL/Web_Technology_2026_Lab_Assignments/Assignment_02/students.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, department, age, year)>
<!ATTLIST student id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== Vedkhajone/WTL/Web_Technology_2026_Lab_Assignments/Assignment_02/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">

<students>
    <student id="S1">
        <name>Pradnya Pangavhane</name>
        <department>Electronics and Computer Engineering</department>
        <age>21</age>
        <year>Third Year</year>
    </student>

    <student id="S2">
        <name>Shreya Sharma</name>
        <department>Computer Science</department>
        <age>22</age>
        <year>Final Year</year>
    </student>

    <student id="S3">
        <name>Rahul Patel</name>
        <department>AI/ML</department>
        <age>20</age>
        <year>Second Year</year>
    </student>

</students>
